/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoeng_degu_utils_JniUtils */

#ifndef _Included_com_aoeng_degu_utils_JniUtils
#define _Included_com_aoeng_degu_utils_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aoeng_degu_utils_JniUtils
 * Method:    getMsgFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoeng_degu_utils_JniUtils_getMsgFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_aoeng_degu_utils_JniUtils
 * Method:    getMsgFromJniCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoeng_degu_utils_JniUtils_getMsgFromJniCpp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
