/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aoeng_degu_utils_JNIUtils */

#ifndef _Included_com_aoeng_degu_utils_JNIUtils
#define _Included_com_aoeng_degu_utils_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_aoeng_degu_utils_JNIUtils
 * Method:    msgFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_aoeng_degu_utils_JNIUtils_msgFromJNI
  (JNIEnv *, jclass);

/*
 * Class:     com_aoeng_degu_utils_JNIUtils
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_aoeng_degu_utils_JNIUtils_getSum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_aoeng_degu_utils_JNIUtils
 * Method:    getFactorial
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_aoeng_degu_utils_JNIUtils_getFactorial
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_aoeng_degu_utils_JNIUtils
 * Method:    getArraySort
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_aoeng_degu_utils_JNIUtils_getArraySort
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
